### ISSUE TITLE
[feat] Workout API 연동

### ISSUE THREAD

**Issue by annapo99** [depromeet/gather-move-iOS#116]
## 👀 Issue

아주 많은 흐린눈 들이 있습니다.

### ✅ Todo
- [ ] 워치가 안켜진 상황에 대한 로직 및 화면 처리
- [ ] 운동이 끝나면 workout session을 종료 시킴
- [ ] calorie 계산 로직에 예외 케이스를 고민
- [ ] 워치에서 iOS를 컨트롤 하는 상황의 케이스 고민
